### ISSUE TITLE
New business rules

### ISSUE THREAD

**Issue by pmaldonado-espol** [lurapozo/ISII-WORKSHOPS-PEDIDOS_EN_LINEA#3]
Dear support team, we are satisfied about your hard work during this last year. On this new year we want to be bigger and better. In the meeting with the Accounting Department and Business Intelligent Group, we proposed some changes with the intention of improving our service and getting more customers. The new business rule establishes: If the customer is married and has more than 30 years old but younger than 60, then $50 must be decreased to the base premium for each one, however if the customer is single, woman and older than 60 years old , she will receive a discount for around $50.

You need to know that all rules should be maintained how it was coming. Our request should be added to the existing one and the result should be calculated with all rules applied.

**Comment by PiscoJuan** [comment]
We have received your issue and we are doing our part in fixing it.

**Comment by PiscoJuan** [comment]
We have categorized your issue.

**Comment by PiscoJuan** [comment]
We will proceed to process the request, @PiscoJuan will be the assigned analyst, @lurapozo will develop the solution and @Rjzaruma will perform the tests.

**Comment by PiscoJuan** [comment]
[AnalysisReport.ods](https://github.com/lurapozo/ISII-WORKSHOPS-PEDIDOS_EN_LINEA/files/10430564/AnalysisReport.ods)
@pmaldonado-espol

**Comment by pmaldonado-espol** [comment]
> [AnalysisReport.ods](https://github.com/lurapozo/ISII-WORKSHOPS-PEDIDOS_EN_LINEA/files/10430564/AnalysisReport.ods)
> @pmaldonado-espol

send it as PDF, please.

**Comment by PiscoJuan** [comment]
[AnalysisReport.pdf](https://github.com/lurapozo/ISII-WORKSHOPS-PEDIDOS_EN_LINEA/files/10438127/AnalysisReport.pdf)
@pmaldonado-espol

**Comment by pmaldonado-espol** [comment]
> [AnalysisReport.pdf](https://github.com/lurapozo/ISII-WORKSHOPS-PEDIDOS_EN_LINEA/files/10438127/AnalysisReport.pdf)
> @pmaldonado-espol

It's OK.

**Comment by lurapozo** [comment]
The code has been updated with the new rules:

https://github.com/lurapozo/ISII-WORKSHOPS-PEDIDOS_EN_LINEA/blob/15f3a2ef7ec37c992070ab095d17859c141ee447/ec.edu.espol.workshops/lib/src/main/java/ec/edu/espol/workshops/CarInsurance.java#L26-L32

**Comment by Rjzaruma** [comment]
[Test Plan.pdf](https://github.com/lurapozo/ISII-WORKSHOPS-PEDIDOS_EN_LINEA/files/10453045/Test.Plan.pdf)

@pmaldonado-espol

**Comment by PiscoJuan** [comment]
@pmaldonado-espol , the solution has been completed, @lurapozo  will relase a version for you

**Comment by lurapozo** [comment]
For the new version to be used it is need to have Eclipse 2021-2019. It is needed to clone the repository and change to the Issues-Management branch.
The new version can be executed in ISII-WORKSHOPS-PEDIDOS_EN_LINEA/ec.edu.espol.workshops/lib/src/main/java/ec/edu/espol/workshops/Insurance.java. Go to that route in Eclipse and select the button Run. 
![image](https://user-images.githubusercontent.com/74026143/213562275-f513fbc3-aefb-4ae1-b675-f3930442cc6c.png)
The program will by executed in the Eclipse terminal question by question, answer using the default values shown in each question.
Example:
![image](https://user-images.githubusercontent.com/74026143/213562381-55d7200a-2660-4c41-aace-ca3200ee9f88.png)

**Comment by PiscoJuan** [comment]
@pmaldonado-espol Are you staisfied with the solution? Were you able to use the software?

**Comment by pmaldonado-espol** [comment]
> @pmaldonado-espol Are you staisfied with the solution? Were you able to use the software?

Yeap, no more changes are needed, thank you.
